set autoindent                                                                                                  
set backspace=indent,eol,start                                                                                  
set expandtab                                                                                                   
set hlsearch                                                                                                    
set ignorecase                                                                                                  
set incsearch                                                                                                   
set laststatus=2                                                                                                
set nocompatible                                                                                                
set number                                                                                                      
set paste                                                                                                       
set showcmd                                                                                                     
set showmatch                                                                                                   
set smartcase                                                                                                   
set smartindent                                                                                                 
set tabstop=4                                                                                                   
set title                                                                                                       
set wrapscan                                                                                                    
syntax enable                                                                                                   
syntax on                                                                                                       
filetype on                                                                                                     
au BufNewFile,BufRead *.hql,*.hiverc  set filetype=sql 
